// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGsjkrHLXrUj1A-_DGG4mIolYDdlsYXno',
    appId: '1:453872297129:web:6f094205b41df71681f5b8',
    messagingSenderId: '453872297129',
    projectId: 'e-commercefruits',
    authDomain: 'e-commercefruits.firebaseapp.com',
    storageBucket: 'e-commercefruits.firebasestorage.app',
    measurementId: 'G-E6BLYHGR4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzfGBKDZS9cSJJoMmBntA-Bxa6N13HQw',
    appId: '1:453872297129:android:94711affc53ac49181f5b8',
    messagingSenderId: '453872297129',
    projectId: 'e-commercefruits',
    storageBucket: 'e-commercefruits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr8mCXXveIarszdZW_ujchRLt1rEuv5Eo',
    appId: '1:453872297129:ios:f61a9a10204762b881f5b8',
    messagingSenderId: '453872297129',
    projectId: 'e-commercefruits',
    storageBucket: 'e-commercefruits.firebasestorage.app',
    iosBundleId: 'com.example.ecommercefrutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr8mCXXveIarszdZW_ujchRLt1rEuv5Eo',
    appId: '1:453872297129:ios:f61a9a10204762b881f5b8',
    messagingSenderId: '453872297129',
    projectId: 'e-commercefruits',
    storageBucket: 'e-commercefruits.firebasestorage.app',
    iosBundleId: 'com.example.ecommercefrutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGsjkrHLXrUj1A-_DGG4mIolYDdlsYXno',
    appId: '1:453872297129:web:f9441b446cf1b3cd81f5b8',
    messagingSenderId: '453872297129',
    projectId: 'e-commercefruits',
    authDomain: 'e-commercefruits.firebaseapp.com',
    storageBucket: 'e-commercefruits.firebasestorage.app',
    measurementId: 'G-TGTK32HNB0',
  );
}
